### ISSUE TITLE
Many-to-one id is not being read from json

### ISSUE THREAD

**Issue by jbeck111** [mikaelhg/kotlin-spring-boot-data-rest#2]
When I post a json record to /menus, it does not read the restaurant_id, and fails to join the new menu to the restaurant.  Try posting this:
{
  "date" : "2017-01-21",
  "title" : "Jellyfish Stew",
  "text" : "Slimy but delicious",
  "restaurant_id" : 1
}
... (where restaurant 1 is the Helsinki restaurant already set up beforehand). The number 1 is read as null; the Helsinki restaurant is not joined, and the menu does not appear against the restaurant.  I tried other entries for "restaurant_id". It quietly allows the string "1", and the non-existent restaurant 123, but converts these also to null.

**Comment by mikaelhg** [comment]
Take a look at http://www.baeldung.com/spring-data-rest-relationships for an explanation of how to set references.
